# Generated by Django 4.2.6 on 2023-10-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jupiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('diameter', models.FloatField(help_text='Diameter in kilometers')),
                ('distance_from_sun', models.FloatField(help_text='Distance from Sun in Astronomical units')),
                ('mass', models.FloatField(help_text='Mass relected in Earth masses')),
                ('orbital_period', models.FloatField(help_text='Orbital period reflected in Earth days')),
                ('rotation_period', models.FloatField(help_text='Rotational period reflected in hours')),
            ],
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('diameter', models.FloatField(help_text='Diameter in Kilometer')),
                ('orbital_period', models.FloatField(help_text='Orbital period reflected in Earth days')),
                ('distance_from_jupiter', models.FloatField(help_text='Average distance measured in kilometers')),
            ],
        ),
    ]
