# Generated by Django 4.2.6 on 2023-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupiter',
            name='diameter',
            field=models.FloatField(help_text='Diameter in Miles'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='diameter',
            field=models.FloatField(help_text='Diameter in Miles.'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='distance_from_jupiter',
            field=models.FloatField(help_text='Average distance measured in Miles.'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='orbital_period',
            field=models.FloatField(help_text='Orbital period reflected in Earth days.'),
        ),
    ]
